name: 'Dependabot Secure Validation'
description: 'Validates that dependency updates do not break the build.'
author: 'EthanThePhoenix38'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  build-command:
    description: 'Command to validate the project'
    required: false
    default: 'npm install && npm run build'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run Build Validation
      shell: bash
      run: ${{ inputs.build-command }}
