name: 'Dependabot Secure Validation'
description: 'Validates and auto-corrects dependency updates by running build checks'
author: 'EthanThePhoenix38'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  node-version:
    description: 'Node.js version to use for validation'
    required: false
    default: '20'
  build-command:
    description: 'Command to run to validate the build'
    required: false
    default: 'npm run build'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Dependencies
      shell: bash
      run: npm install --prefer-offline --no-audit

    - name: Validate Build
      shell: bash
      run: ${{ inputs.build-command }}
